name: Sync Rules

on:
  push:
    paths:
      - 'rules/Loon/Self-Direct.list'
      - 'rules/Loon/Self-Proxy.list'
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Sync rules
        run: |
          python .github/scripts/sync_rules.py
          
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add rules/Clash/Self-Direct.yaml rules/Clash/Self-Proxy.yaml
          git add rules/QuanX/Self-Direct.list rules/QuanX/Self-Proxy.list
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: sync rules from Loon to Clash and QuanX" && git push)
